spring.application.name=Spring-Blog-Engine

jwt.secret=jwt.secret=8FfKx2qL9vR7mN4sTzY1pWc6JdHbUaEeQrTyUiOpLmNoPqRsTuVwXyZaBcDeFgHi

cloudinary.cloud-name=xxx
cloudinary.api-key=xxx
cloudinary.api-secret=xxx


